{% set version = "4.0.0" %}

package:
  name: gitdb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gitdb/gitdb-{{ version }}.tar.gz
  sha256: 1bad024b93eb39e01641acf88809b25293d7f4d8fa4d2ff229069a91130a8e2c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - smmap >=0.8.3

test:
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Git Object Database'

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
