{% set version = "4.0.2" %}

package:
  name: gitdb
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/gitdb/gitdb-{{ version }}.tar.gz
  sha256: 598e0096bb3175a0aab3a0b5aedaa18a9a25c6707e0eca0695ba1a0baf1b2150

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - python >=3.4
    - smmap >=3.0.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - gitdb
    - gitdb.db

about:
  home: https://github.com/gitpython-developers/gitdb
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Git Object Database

extra:
  recipe-maintainers:
    - pelson
    - ocefpaf
