appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: F49Op4e2LCLbu9jZA61nne9QVimpRVqIDLDdfSBYmjXngWa4r3jzArIQQ+hVE5/CEkkXjCug7Uw23T81VvihJp8spTXwQSnQHKdXItsWztKvAi8m2A6Nns+6ZFsyk93xYbrWUEqJQYFOSg+h3KqtR4/8Immz2JS3jPUFJtt+c4uoOUvyhzJi3DHBMUtdymNYa7K+AfafHUmjJo4qI8ZcPx6wd+SLAcMBTfBJE7BZKW5xMXsi42I5ZdBXAq6v6A/api8lz0iyfa+IMNOrFPEahaAQ+5T56WOPl5bKyxv66jkhnBvmyEdzN0ksBcefSuSGDmbO4JXCZuFR4A7HqD2zbhihsVljJNHSTMlegHhIHeY3M32KGowgELZ6oiJAu0PjmIfbKh0/0SIq3JQ3sYRH6MXp/eYhLpPIh/i5pTdR/08G4EoQa65fmGHw1Tz+mFnsoqheiwErJPOqRkvS2GWDhG4YOhl8vMsHQgh0V79uKjdIWDLQFns/SRarsAeFOC2yNAutULuv6ZWIpyQXaxFGgs+PKMZBX3bOzTGIccCePCvrunrBUMQh3sINeIKsX6lenZuM8KgoGebtHpPdnPHNH5T3LE5SwiXGq9nz+aRJB3kwj9M24+SYA/jXnhipAww63sj8FwHbJ9f0Fw5eoyvNW9gsSeRVDxb6FWct9h7xUyw=}
bot:
  automerge: true
conda_forge_output_validation: true
